---
# Foundation completion validation
- name: Check if admin directory exists
  shell: |
    if [ ! -d "{{ ansible_env.adminDir }}" ]; then
      echo "ERROR: Required directory {{ ansible_env.adminDir }} does not exist"
      echo "Please run install-prep.sh first to create admin directories"
      exit 1
    fi
    echo "Admin directory exists: {{ ansible_env.adminDir }}"
  register: admin_check
  failed_when: admin_check.rc != 0

- name: Check if backup directory exists
  shell: |
    if [ ! -d "{{ ansible_env.backup_dir }}" ]; then
      echo "ERROR: Required directory {{ ansible_env.backup_dir }} does not exist"
      echo "Please run install-prep.sh first to create admin directories"
      exit 1
    fi
    echo "Backup directory exists: {{ ansible_env.backup_dir }}"
  register: backup_check
  failed_when: backup_check.rc != 0

- name: Verify GitHub key in known_hosts
  shell: |
    if ! grep -q "^{{ ansible_env.host_remote }}" "{{ ansible_env.knownHosts }}"; then
      echo "ERROR: GitHub key not found in {{ ansible_env.knownHosts }}"
      exit 1
    fi
    echo "GitHub key found in known_hosts"
  register: github_check
  failed_when: github_check.rc != 0

- name: Verify solarized theme exists
  shell: |
    if [ ! -d "{{ ansible_env.termStuff }}/solarized" ]; then
      echo "ERROR: Solarized theme not found at {{ ansible_env.termStuff }}/solarized"
      exit 1
    fi
    echo "Solarized theme found"
  register: solarized_check
  failed_when: solarized_check.rc != 0

- name: Foundation validation summary
  debug:
    msg: |
      Foundation setup validation PASSED:
      ✓ Admin directories exist
      ✓ GitHub SSH key configured
      ✓ Solarized theme downloaded
      ✓ Ready for next phase
