---
# Pre-flight validation tasks
- name: Check if running on macOS
  fail:
    msg: "This automation is designed for macOS only"
  when: ansible_os_family != "Darwin"

- name: Check for required environment variables
  fail:
    msg: "Required environment variable {{ item }} is not defined or empty"
  when: ansible_env[item] is not defined or ansible_env[item] == ""
  loop:
    - myFullName
    - myEmailAdd
    - myMBPisFor
    - adminDir

- name: Display validated configuration
  debug:
    msg: |
      Configuration validated:
      - User: {{ ansible_env.myFullName }}
      - Email: {{ ansible_env.myEmailAdd }}
      - MBP Purpose: {{ ansible_env.myMBPisFor }}
      - Admin Directory: {{ ansible_env.adminDir }}
      - Environment: {{ env_mode }}
