# SSH key management - simplified using Ansible's known_hosts module
# File: ansible/tasks/configure/ssh-keys.yml
---
- name: Scan GitHub SSH key
  shell: ssh-keyscan -t rsa {{ ansible_env.host_remote }} | grep -v '^#'
  register: github_key_scan
  changed_when: false

- name: Add GitHub SSH key to known_hosts
  ansible.builtin.known_hosts:
    name: "{{ ansible_env.host_remote }}"
    key: "{{ github_key_scan.stdout }}"
    path: "{{ ansible_env.knownHosts }}"
    state: present
  register: github_key_result
  tags: [base]

- name: Display GitHub key status
  debug:
    msg: "GitHub SSH key {% if github_key_result.changed %}added to{% else %}already present in{% endif %} {{ ansible_env.knownHosts }}"
  tags: [base]
