---
# System backups - corresponds to bootstrap.sh lines ~95-105
- name: Display backup operation start
  debug:
    msg: "Backing up the /etc directory before we begin..."

- name: Check if backup directory exists
  ansible.builtin.stat:
    path: "{{ ansible_env.backup_dir }}"
  register: backup_dir_check

- name: Fail if backup directory missing
  fail:
    msg: "Backup directory {{ ansible_env.backup_dir }} does not exist"
  when: not backup_dir_check.stat.exists

- name: Backup /etc directory for testing
  shell: rsync -aE /private/etc "{{ ansible_env.backup_dir }}/"
  register: backup_result
  failed_when: backup_result.rc != 0
  become: yes
  ignore_errors: yes

- name: Check for backup errors
  debug:
    msg: "Backup completed. Check /tmp/rsync-err-etc.out for any errors"
  when: backup_result.rc == 0

- name: Display backup failure warning
  debug:
    msg: "Warning: Backup operation had issues. Check system permissions."
  when: backup_result.rc != 0
