# Install and configure Rust programming language
# File: roles/rust/tasks/main.yml
---
- name: Install Rust
  community.general.homebrew:
    name: rust
    state: present
  register: rust_install

- name: Configure Rust system path
  ansible.builtin.lineinfile:
    path: /etc/paths
    insertbefore: '^/usr/local/bin$'
    line: '$HOME/.cargo/bin'
  become: yes
  register: rust_path

- name: Copy Rust environment configuration
  ansible.builtin.copy:
    src: rust.zsh
    dest: "$HOME/.oh-my-zsh/custom/rust.zsh"
    mode: '0644'
  register: rust_config

- name: Display Rust setup status
  debug:
    msg:
      - "Rust setup completed:"
      - "  - Package: {% if rust_install.changed %}installed{% else %}already present{% endif %}"
      - "  - System path: {% if rust_path.changed %}configured{% else %}already configured{% endif %}"
      - "  - Shell config: {% if rust_config.changed %}deployed{% else %}already present{% endif %}"
