---
# System utilities installation
- name: Install networking and system utilities
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - cfssl
    - dockutil
    - dos2unix
    - ipcalc
    - jid
    - jq
    - libressl
    - nmap
    - psgrep
    - pstree
    - rsync
    - sipcalc
    - ssh-copy-id
    - tcpdump
    - testdisk
    - tmux
    - tree
    - watch
    - whatmask
    - yq
  register: network_utils

- name: Install build utilities
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - cmake
    - bazel
  register: build_utils

- name: Check if /etc/paths exists
  ansible.builtin.stat:
    path: /etc/paths
  register: paths_check

- name: Add libressl to system path
  ansible.builtin.lineinfile:
    path: /etc/paths
    line: "/opt/homebrew/opt/libressl/bin"
    insertbefore: "/usr/local/bin"
    create: no
  become: yes
  when: paths_check.stat.exists
  register: libressl_path

- name: Display system utilities installation status
  debug:
    msg:
      - "System utilities installation completed:"
      - "  - Network utilities: {% if network_utils.changed %}installed{% else %}already present{% endif %}"
      - "  - Build utilities: {% if build_utils.changed %}installed{% else %}already present{% endif %}"
      - "  - LibreSSL path: {% if libressl_path.changed %}added{% else %}already present{% endif %}"
