# Foundational setup
---
- name: Foundation Setup
  hosts: remote_macos
  gather_facts: yes
  vars:
    time_pre: "{{ ansible_date_time.time }}"
    homebrew_no_env_hints: true

  environment:
    HOMEBREW_NO_ENV_HINTS: "{{ homebrew_no_env_hints }}"

  tasks:
    - name: Kick-off message
      debug:
        msg: |
          Configuring this macOS for {{ ansible_env.myFullName }}
          Environment mode: {{ env_mode }}
          Start time: {{ time_pre }}

    - name: Show test warning if in TEST mode
      debug:
        msg: "THIS IS ONLY A TEST"
      when: env_mode == "TEST"

    - name: Show live confirmation if in LIVE mode
      debug:
        msg: "We are preparing to go live..."
      when: env_mode != "TEST"

    - name: Pre-flight validation
      include_tasks:
        file: ../tasks/validate/prereqs.yml
        apply:
          tags: [foundation]
      tags: [foundation]

    # SSH key management (now with base tag)
    - name: Configure SSH keys
      include_tasks:
        file: ../tasks/configure/ssh-keys.yml
        apply:
          tags: [base]
      tags: [base]

    # System backups (conditional)
    - name: Perform system backups
      include_tasks: ../tasks/configure/system-backups.yml
      when: env_mode == "TEST"

    # Terminal setup prerequisites
    - name: Setup terminal prerequisites
      include_tasks: ../tasks/configure/terminal-prereqs.yml

    # # Post-configuration validation
    # - name: Foundation validation
    #   include_tasks:
    #     file: ../tasks/validate/foundation-complete.yml
    #     apply:
    #       tags: [foundation]
    #   tags: [foundation]

    # Facts collection at the end
    - name: Ensure admin logs directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.adminLogs }}"
        state: directory
        mode: '0755'

    - name: Save system facts to JSON file
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ ansible_env.adminLogs }}/facts-{{ inventory_hostname }}.json"
        mode: '0644'
      register: facts_saved

    - name: Display facts report location
      debug:
        msg: "System facts saved to {{ ansible_env.adminLogs }}/facts-{{ inventory_hostname }}.json"

    # Confirm Success
    - name: Display foundation completion
      debug:
        msg: "Foundation setup completed successfully"
