---
# Terminal prerequisites - corresponds to bootstrap.sh lines ~110-120
- name: Terminal Setup
  hosts: local
  gather_facts: no

  tasks:
    - name: Display terminal setup start
      debug:
        msg: "Pulling Terminal stuff..."

    - name: Ensure terminal downloads directory exists
      file:
        path: "{{ ansible_env.termStuff }}"
        state: directory
        mode: '0755'

    - name: Clone Solarized terminal theme
      git:
        repo: "{{ ansible_env.solarizedGitRepo }}"
        dest: "{{ ansible_env.termStuff }}/solarized"
        clone: yes
        update: yes
      register: solarized_clone

    - name: Display solarized clone status
      debug:
        msg: "Solarized theme {% if solarized_clone.changed %}cloned{% else %}already present{% endif %} at {{ ansible_env.termStuff }}/solarized"

    - name: Check for existing settings to restore
      stat:
        path: "{{ ansible_env.myBackups }}"
      register: backup_check

    - name: Display settings restore status
      debug:
        msg: "{% if backup_check.stat.exists %}Settings backup found - will be restored{% else %}No settings backup found to restore{% endif %}"

    - name: Restore terminal settings if available
      shell: rsync -aEv "{{ ansible_env.myBackups }}/Documents/system" "{{ my_docs }}/"
      when: backup_check.stat.exists
      register: settings_restore
      ignore_errors: yes

    - name: Display settings restore result
      debug:
        msg: "Settings restore {% if settings_restore.rc == 0 %}completed successfully{% else %}had issues - check /tmp/rsync-err-system.out{% endif %}"
      when: backup_check.stat.exists
