# macOS system configuration
---
- name: Configure hostname settings (personal MBP only)
  block:
    - name: Set computer name
      ansible.builtin.command:
        cmd: "scutil --set ComputerName {{ ansible_env.myHostName }}"
      become: yes
      register: computer_name
      changed_when: true

    - name: Set terminal hostname
      ansible.builtin.command:
        cmd: "scutil --set HostName {{ ansible_env.myHostName.split('.')[0] }}"
      become: yes
      register: host_name
      changed_when: true

    - name: Set AirDrop hostname
      ansible.builtin.command:
        cmd: "scutil --set LocalHostName {{ ansible_env.myHostName.split('.')[0] }}"
      become: yes
      register: local_host_name
      changed_when: true
  when: ansible_env.myMBPisFor == "personal"

- name: Configure storage preferences
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  register: storage_prefs

- name: Disable smart quotes system-wide
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  register: smart_quotes

- name: Disable smart dashes system-wide
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  register: smart_dashes

- name: Configure Finder preferences
  community.general.osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - { key: "FXPreferredViewStyle", type: "string", value: "Nlsv" }  # List view
    - { key: "NewWindowTarget", type: "string", value: "PfLo" }      # Home directory
    - { key: "NewWindowTargetPath", type: "string", value: "file://{{ ansible_env.HOME }}/" }
    - { key: "ShowStatusBar", type: "bool", value: true }
    - { key: "FXDefaultSearchScope", type: "string", value: "SCcf" }  # Current folder
  register: finder_prefs

- name: Show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  register: show_extensions

- name: Create screenshots directory
  ansible.builtin.file:
    path: "{{ ansible_env.myPics }}/screens"
    state: directory
    mode: '0755'
  register: screenshots_dir

- name: Configure screenshot location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.myPics }}/screens"
  register: screenshot_location

- name: Disable screenshot shadows
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  register: screenshot_shadows

- name: Create screenshots symlink on Desktop
  ansible.builtin.file:
    src: "{{ ansible_env.myPics }}/screens"
    dest: "{{ ansible_env.myDesktop }}/screens"
    state: link
  register: screenshots_link

- name: Show battery percentage
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"
  register: battery_percentage

- name: Configure menu bar clock format
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "EEE MMM d  h:mm a"
  register: clock_format

- name: Configure Dock preferences
  community.general.osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - { key: "tilesize", type: "float", value: 42.0 }
    - { key: "autohide", type: "bool", value: true }
    - { key: "autohide-delay", type: "float", value: 0.0 }
    - { key: "autohide-time-modifier", type: "float", value: 0.0 }
  register: dock_prefs

- name: Configure security settings
  block:
    - name: Disable guest user at login screen
      community.general.osx_defaults:
        domain: /Library/Preferences/com.apple.loginwindow
        key: GuestEnabled
        type: bool
        value: false
      become: yes
      register: guest_disabled

    - name: Disable AFP guest access
      community.general.osx_defaults:
        domain: com.apple.AppleFileServer
        key: AllowGuestAccess
        type: int
        value: 0
      register: afp_guest

- name: Configure Photos app behavior
  community.general.osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: true
    host: currentHost
  register: photos_hotplug

- name: Configure TextEdit preferences
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - { key: "author", type: "string", value: "{{ ansible_env.myFullName }}" }
    - { key: "RichText", type: "int", value: 0 }
    - { key: "NSFixedPitchFont", type: "string", value: "Hack Regular" }
    - { key: "NSFixedPitchFontSize", type: "string", value: 14 }
    - { key: "WidthInChars", type: "int", value: 100 }
    - { key: "HeightInChars", type: "int", value: 45 }
    - { key: "SmartDashes", type: "int", value: 0 }
    - { key: "SmartQuotes", type: "int", value: 0 }
  register: textedit_prefs

- name: Configure network shares behavior
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  register: network_stores

- name: Configure dialog box preferences
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    type: bool
    value: true
  loop:
    - { key: "NSNavPanelExpandedStateForSaveMode" }
    - { key: "NSNavPanelExpandedStateForSaveMode2" }
    - { key: "PMPrintingExpandedStateForPrint" }
    - { key: "PMPrintingExpandedStateForPrint2" }
  register: dialog_prefs

- name: Display macOS configuration status
  debug:
    msg:
      - "macOS configuration completed:"
      - "  - Hostname: {% if ansible_env.myMBPisFor == 'personal' %}configured{% else %}skipped (work MBP){% endif %}"
      - "  - Storage preferences: {% if storage_prefs.changed %}configured{% else %}already set{% endif %}"
      - "  - Smart text features: {% if smart_quotes.changed or smart_dashes.changed %}disabled{% else %}already disabled{% endif %}"
      - "  - Finder preferences: {% if finder_prefs.changed %}configured{% else %}already set{% endif %}"
      - "  - Screenshot settings: {% if screenshot_location.changed %}configured{% else %}already set{% endif %}"
      - "  - Dock preferences: {% if dock_prefs.changed %}configured{% else %}already set{% endif %}"
      - "  - Security settings: {% if guest_disabled.changed %}configured{% else %}already set{% endif %}"
      - "  - TextEdit preferences: {% if textedit_prefs.changed %}configured{% else %}already set{% endif %}"
