# Install and configure Kubernetes CLI with ktx
# File: roles/kubernetes/tasks/main.yml
---
- name: Install Kubernetes CLI
  community.general.homebrew:
    name: kubernetes-cli
    state: present
  register: app_install

- name: Clone ktx repository
  ansible.builtin.git:
    repo: https://github.com/heptiolabs/ktx
    dest: /tmp/ktx
    force: yes
  register: ktx_clone

- name: Install ktx bash function
  ansible.builtin.copy:
    src: /tmp/ktx/ktx
    dest: "{{ ansible_env.HOME }}/.ktx"
    mode: '0755'
    remote_src: yes
  register: ktx_install

- name: Install ktx completion
  ansible.builtin.copy:
    src: /tmp/ktx/ktx-completion.sh
    dest: "{{ ansible_env.HOME }}/.ktx-completion.sh"
    mode: '0644'
    remote_src: yes
  register: ktx_completion

- name: Clean up ktx temporary directory
  ansible.builtin.file:
    path: /tmp/ktx
    state: absent

- name: Copy Kubernetes CLI environment configuration
  ansible.builtin.copy:
    src: kubernetes.zsh
    dest: "$HOME/.oh-my-zsh/custom/kubernetes.zsh"
    mode: '0644'
  register: env_config

- name: Display Kubernetes CLI setup status
  debug:
    msg:
      - "Kubernetes CLI setup completed:"
      - "  - kubectl: {% if app_install.changed %}installed{% else %}already present{% endif %}"
      - "  - ktx function: {% if ktx_install.changed %}installed{% else %}already present{% endif %}"
      - "  - ktx completion: {% if ktx_completion.changed %}installed{% else %}already present{% endif %}"
      - "  - Shell config: {% if env_config.changed %}deployed{% else %}already present{% endif %}"
